// Shared page chrome
(function(){
  const ANNOUNCE = `<div class="announce-small"><div class="wrap announce-inner"><span class="mono">NEW · V2</span><span>SmartPad now writes across 9 languages in real time.</span><a class="ilink" href="product.html" style="margin-left:auto;">Read the release notes <span class="arr"></span></a></div></div>`;
  const NAV = (a) => `<header class="nav"><div class="wrap nav-inner"><a href="index.html" class="logo"><span class="logo-mark">त</span><span>TatvaPractice</span></a><nav><ul><li><a href="product.html" class="${a==='product'?'active':''}">Product</a></li><li><a href="pricing.html" class="${a==='pricing'?'active':''}">Pricing</a></li><li><a href="resources.html" class="${a==='resources'?'active':''}">Resources</a></li><li><a href="about.html" class="${a==='about'?'active':''}">About</a></li><li><a href="dashboard.html" class="${a==='dashboard'?'active':''}">Dashboard</a></li></ul></nav><div class="nav-cta"><a href="signin.html" class="btn btn-ghost">Sign in</a><a href="demo.html" class="btn btn-primary">Book a demo <span class="arr"></span></a></div></div></header>`;
  const FOOTER = `<footer class="footer"><div class="wrap footer-grid"><div class="footer-brand"><a href="index.html" class="logo on-dark"><span class="logo-mark on-dark">त</span><span>TatvaPractice</span></a><p class="footer-tag">AI-native EMR for Indian clinicians.<br/>Built in Bengaluru. Hosted in Mumbai.</p><div class="chip on-dark"><span class="dot"></span> All systems operational</div></div><div><div class="mono">Product</div><ul><li><a href="product.html#smartpad">SmartPad</a></li><li><a href="product.html#voicerx">VoiceRx</a></li><li><a href="product.html#assistant">Clinical Assistant</a></li><li><a href="pricing.html">Pricing</a></li><li><a href="dashboard.html">Owner dashboard</a></li></ul></div><div><div class="mono">Company</div><ul><li><a href="about.html">About</a></li><li><a href="resources.html">Resources</a></li><li><a href="#">Careers</a></li><li><a href="#">Press</a></li></ul></div><div><div class="mono">Get in touch</div><ul><li><a href="demo.html">Book a demo</a></li><li><a href="mailto:hello@tatva.health">hello@tatva.health</a></li><li><a href="tel:+918040000000">+91 80 4000 0000</a></li><li>HSR Layout, Bengaluru</li></ul></div></div><div class="wrap footer-foot"><span class="mono">© 2026 Tatva Health Pvt. Ltd.</span><span class="mono">v 2.0 · April 2026</span><span class="mono"><a href="#">Privacy</a> · <a href="#">Terms</a> · <a href="#">DPDP</a></span></div></footer>`;

  function mount(){
    const a = document.querySelector('[data-slot="announce"]'); if (a) a.outerHTML = ANNOUNCE;
    const n = document.querySelector('[data-slot="nav"]'); if (n) n.outerHTML = NAV(n.dataset.active || '');
    const f = document.querySelector('[data-slot="footer"]'); if (f) f.outerHTML = FOOTER;
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount);
  else mount();
})();
